module.exports = {
  extends: ['eslint:recommended'],
  parser: '@babel/eslint-parser',
  rules: {
    'array-callback-return': ['error'],
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-parens': ['error', 'as-needed'],
    'camelcase': ['error', {
      allow: ['[a-zA-Z0-9]+__[a-zA-Z0-9]+'],
      properties: 'always',
      ignoreDestructuring: true,
      ignoreGlobals: true,
      ignoreImports: true,
    }],
    'comma-dangle': ['error', {
      arrays: 'always-multiline',
      exports: 'always-multiline',
      functions: 'never',
      imports: 'always-multiline',
      objects: 'always-multiline',
    }],
    'complexity': ['error', 25],
    'consistent-return': ['error'],
    'curly': ['error', 'all'],
    'eqeqeq': ['error', 'always'],
    'indent': ['error', 2],
    'jsx-quotes': ['error', 'prefer-double'],
    'linebreak-style': ['error', 'unix'],
    'max-depth': ['error', 5],
    'max-len': ['error', { code: 100, ignoreUrls: true, tabWidth: 2 }],
    'max-lines': ['error', 500],
    'max-lines-per-function': ['error', 200],
    'max-statements': ['error', 20, {
      ignoreTopLevelFunctions: true,
    }],
    'no-constructor-return': ['error'],
    'no-duplicate-imports': ['error'],
    'no-extra-parens': ['error'],
    'no-implicit-coercion': ['error'],
    'no-multi-spaces': ['error'],
    'no-self-compare': ['error'],
    'no-tabs': ['error'],
    'no-throw-literal': ['error'],
    'no-trailing-spaces': ['error'],
    'no-underscore-dangle': ['error'],
    'no-unneeded-ternary': ['error'],
    'no-unreachable-loop': ['error'],
    'no-unused-private-class-members': ['error'],
    'no-unused-vars': ['error', { ignoreRestSiblings: true }],
    'no-useless-computed-key': ['error'],
    'no-useless-concat': ['error'],
    'no-useless-constructor': ['error'],
    'no-useless-rename': ['error'],
    'no-useless-return': ['error'],
    'no-var': ['error'],
    'no-whitespace-before-property': ['error'],
    'object-curly-spacing': ['error', 'always'],
    'object-shorthand': ['error', 'always'],
    'one-var-declaration-per-line': ['error'],
    'prefer-const': ['error'],
    'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
    'prefer-rest-params': ['error'],
    'prefer-spread': ['error'],
    'quote-props': ['error', 'consistent-as-needed'],
    'quotes': ['error', 'single'],
    'radix': ['error'],
    'require-await': ['error'],
    'require-yield': ['error'],
    'rest-spread-spacing': ['error', 'never'],
    'semi': ['error', 'never'],
    'yoda': ['error', 'never'],
  },
}
